name: Setup Publicodes
description: Setup and build publicodes packages with caching
runs:
  using: composite
  steps:
    - name: Cache publicodes builds
      uses: actions/cache@v4
      with:
        path: |
          packages/*/publicodes-build
          packages/*/node_modules
        key: publicodes-${{ hashFiles('packages/**/package.json', 'packages/**/src/**', 'pnpm-lock.yaml') }}
        restore-keys: |
          publicodes-
    - name: Build publicodes
      shell: bash
      run: pnpm build:publicodes
