name: Setup Publicodes
description: Setup and build publicodes packages with caching
runs:
  using: composite
  steps:
    - name: Cache publicodes builds
      uses: actions/cache@v4
      with:
        path: |
          publicodes/*/dist
          publicodes/*/node_modules
        key: publicodes-${{ hashFiles('publicodes/**/package.json', 'publicodes/**/pnpm-lock.yaml') }}
        restore-keys: |
          publicodes-
    - name: Build publicodes
      shell: bash
      run: pnpm build:publicodes
