/** THIS FILE WAS GENERATED BY @publicodes/tools (v1.7.2). PLEASE, DO NOT EDIT IT MANUALLY. */

import { Rule } from 'publicodes'

/**
 * String representing a date in the format 'DD/MM/YYYY' or 'MM/YYYY'.
 */
export type PDate = string

/**
 * Publicodes boolean type.
 */
export type PBoolean = 'oui' | 'non'

/**
 * String constant are enclosed in single quotes to differentiate them from
 * references.
 */
export type PString = `'${string}'`

/**
 * Corresponding Publicodes situation with types inferred for each rule.
 *  
 * @note
 * This represents the situation as needed by the 'setSituation' method of the
 * {@link Engine} class with raw values (i.e. string constants are enclosed in
 * "''" and boolean values are 'oui' or 'non').
 */
export type Situation = Partial<{
  "prix": PBoolean,
  "prix . carottes": number,
  "prix . champignons": number,
  "prix . avocat": number,
  "dépenses primeur": number,
  "natureActivite": PBoolean,
  "natureActivite . industrielle": PBoolean,
  "natureActivite . commerciale": PBoolean,
  "natureActivite . agricole": PBoolean,
  "natureActivite . artisanale": PBoolean,
  "natureActivite . autreActivite": PBoolean,
  "situationGeographique": "'metropole'" | "'outremer'",
  "entrepriseEnDifficulte": PBoolean,
  "dateDeCreation": PDate,
  "activiteNouvelle": PBoolean,
  "dirigeantsOuActionnairesUniversitaire": PBoolean,
  "dirigeantsOuActionnairesUniversitaire . etudiant": PBoolean,
  "dirigeantsOuActionnairesUniversitaire . diplomeMaster": PBoolean,
  "dirigeantsOuActionnairesUniversitaire . diplomeDoctorat": PBoolean,
  "dirigeantsOuActionnairesUniversitaire . enseignant": PBoolean,
  "dirigeantsOuActionnairesUniversitaire . aucune": PBoolean,
  "valorisationRecherche": PBoolean,
  "contratValorisation": PBoolean,
  "capitalDetenu": PBoolean,
  "capitalDetenu . personnesPhysiques": PBoolean,
  "capitalDetenu . autreJei": PBoolean,
  "capitalDetenu . associationFondation": PBoolean,
  "capitalDetenu . etablissementPublic": PBoolean,
  "capitalDetenu . societeInvestissement": PBoolean,
  "capitalDetenu . aucune": PBoolean,
  "chiffreAffairesN": number,
  "bilanTotalN": number,
  "effectifTotalN": number,
  "chiffreAffairesN1": number,
  "bilanTotalN1": number,
  "effectifTotalN1": number,
  "chiffreAffairesN2": number,
  "bilanTotalN2": number,
  "effectifTotalN2": number,
  "categorieExoneration": PBoolean,
  "categorieExoneration . jei": PBoolean,
  "categorieExoneration . repriseEntrepriseEnDifficulte": PBoolean,
  "categorieExoneration . zoneSpecifique": PBoolean,
  "categorieExoneration . aucune": PBoolean,
  "categorieExonerationZoneSpecifique": PBoolean,
  "categorieExonerationZoneSpecifique . zfr": PBoolean,
  "categorieExonerationZoneSpecifique . zfuTe": PBoolean,
  "categorieExonerationZoneSpecifique . ber": PBoolean,
  "categorieExonerationZoneSpecifique . zrd": PBoolean,
  "categorieExonerationZoneSpecifique . zfo": PBoolean,
  "categorieExonerationZoneSpecifique . zrr": PBoolean,
  "categorieExonerationZoneSpecifique . frr": PBoolean,
  "categorieExonerationZoneSpecifique . bud": PBoolean,
  "categorieExonerationZoneSpecifique . zdp": PBoolean,
  "pourcentageRd": PBoolean,
  "effectifAugmente": PBoolean,
  "depensesStables": PBoolean,
  "depensesRD": PBoolean,
  "depensesRDAmortissementBiens": PBoolean,
  "depensesRDAmortissementBiensDom": PBoolean,
  "depensesRDIndemnisationAssurance": PBoolean,
  "depensesRDIndemnisationAssuranceDom": PBoolean,
  "depensesRDChercheursTechniciens": PBoolean,
  "depensesRDChercheursTechniciensDom": PBoolean,
  "depensesRDRemunerationInvention": PBoolean,
  "depensesRDRemunerationInventionDom": PBoolean,
  "depensesRDRechercheLiensDependance": PBoolean,
  "depensesRDRechercheLiensDependanceDom": PBoolean,
  "depensesRDRechercheSansLiensDependance": PBoolean,
  "depensesRDRechercheSansLiensDependanceDom": PBoolean,
  "contratOrdc": PBoolean,
  "respecteCriteresOrdc": PBoolean,
  "depensesOrdc": number,
  "subventionsOrdc": number,
  "remboursementsSubventionsOrdc": number,
  "depensesRDSubventionsPubliques": number,
  "depensesRDDepensesConseil": number,
  "depensesRDDepensesTiersCir": number,
  "depensesNormalisationSalaires": number,
  "depensesNormalisationSalairesDom": number,
  "depensesNormalisationDirigeant": number,
  "depensesNormalisationDirigeantDom": number,
  "depensesNormalisationRemboursementSubventions": number,
  "depensesNormalisationSubventions": number,
  "depensesNormalisationConseil": number,
  "depensesPrototypeAmortissementsImmobilisations": number,
  "depensesPrototypeAmortissementsImmobilisationsDom": number,
  "depensesPrototypeAmortissementsImmobilisationsCorse": number,
  "depensesPrototypeChercheursTechniciens": number,
  "depensesPrototypeRemunerationInvention": number,
  "depensesPrototypeAmortissementsBrevets": number,
  "depensesPrototypeAmortissementsBrevetsDom": number,
  "depensesPrototypeAmortissementsBrevetsCorse": number,
  "depensesPrototypeFraisDepotDessins": number,
  "depensesPrototypeFraisDepotDessinsDom": number,
  "depensesPrototypeFraisDepotDessinsCorse": number,
  "depensesPrototypeDepensesSousTraitance": number,
  "depensesPrototypeDepensesSousTraitanceDom": number,
  "depensesPrototypeDepensesSousTraitanceCorse": number,
  "depensesPrototypeRemboursementsSubventions": number,
  "depensesPrototypeSubventionsPubliques": number,
  "depensesPrototypeDepensesConseil": number,
  "depensesPrototypeDepensesTiersCii": number,
  "chiffreAffairesSelector": PBoolean,
  "chiffreAffairesSelector . yearN": PBoolean,
  "chiffreAffairesSelector . yearN1": PBoolean,
  "chiffreAffairesSelector . yearN2": PBoolean,
  "chiffreAffairesSelector . noBilan": PBoolean,
  "typeDepenses": PBoolean,
  "typeDepenses . rd": PBoolean,
  "typeDepenses . normalisation": PBoolean,
  "typeDepenses . prototype": PBoolean,
  "performancesSuperieures": PBoolean,
  "performancesSuperieures . techniques": PBoolean,
  "performancesSuperieures . eco": PBoolean,
  "performancesSuperieures . ergonomiques": PBoolean,
  "performancesSuperieures . fonctionnalites": PBoolean,
  "performancesSuperieures . performancesSuperieuresAucune": PBoolean,
  "typeDeRevenus": "'bic'" | "'bnc'",
  "regimeFiscal": "'micro'" | "'reel-simplifie'" | "'reel-normal'",
  "typeImposition": "'is'" | "'ir'" | "'exonere'",
  "prototypeDestination": PBoolean,
  "produitMisMarche": PBoolean,
  "depensesRdIndemnisationAssuranceDom": PBoolean,
  "depensesRdIndemnisationAssurance": PBoolean,
  "depensesRdAmortissementBiensDom": PBoolean,
  "depensesRdAmortissementBiens": PBoolean,
  "depensesRdRemunerationInventionDom": PBoolean,
  "depensesRdRemunerationInvention": PBoolean,
  "depensesRdChercheursTechniciensDom": PBoolean,
  "depensesRdChercheursTechniciens": PBoolean,
  "depensesRdRechercheSansLiensDependanceDom": PBoolean,
  "depensesRdRechercheSansLiensDependance": PBoolean,
  "depensesRdRechercheLiensDependanceDom": PBoolean,
  "depensesRdRechercheLiensDependance": PBoolean,
  "depensesRdDepensesTiersCir": PBoolean,
  "depensesRdDepensesConseil": PBoolean,
  "depensesRdSubventionsPubliques": PBoolean,
  "depensesNormalisationRemboursementsSubventions": PBoolean,
  "JEU": PBoolean,
  "JEU . eligibilite": PBoolean,
  "JEI": PBoolean,
  "JEI . eligibilite": PBoolean,
  "JEI . pourcentageRdCondition": PBoolean,
  "JEC": PBoolean,
  "JEC . eligibilite": PBoolean,
  "JEC . conditionAge": PBoolean,
  "JEC . critereRD": PBoolean,
  "Jeune Entreprise": PBoolean,
  "Jeune Entreprise . conditionAge": PBoolean,
  "ageEntreprise": number,
  "regimeFiscalEstReel": PBoolean,
  "estUnePME": PBoolean,
  "CIR": PBoolean,
  "CIR . eligibilite": PBoolean,
  "CIR . montant": number,
  "CIR . creditMetropole": number,
  "CIR . creditDom": number,
  "CIR . depensesMetropole": number,
  "CIR . depensesDom": number,
  "CIR . deductions": number,
  "CIR . deductions . dom": number,
  "CIR . deductions . metropole": number,
  "CII": PBoolean,
  "CII . eligibilite": PBoolean,
  "CII . montant": number | null,
  "CII . montantPlafonne": number,
  "CII . depensesBase": number,
  "CII . depensesDOM": number,
  "CII . depensesCorse": number,
  "CII . tauxCorse": number,
  "CII . deductions": number,
  "CII . depassementEffectifN": PBoolean,
  "CII . depassementEffectifN1": PBoolean,
  "CII . depassementEffectifN2": PBoolean,
  "CII . depassementFinancierN": PBoolean,
  "CII . depassementFinancierN1": PBoolean,
  "CII . depassementFinancierN2": PBoolean,
  "CII . depassementConsecutif": PBoolean,
  "CICo": PBoolean,
  "CICo . eligibilite": PBoolean,
  "CICo . montant": number,
  "CICo . taux": number
}>

/**
 * Associates for each rule name its corresponding value type (in JavaScript
* form) that will be returned by the {@link Engine.evaluate} method.
 */
export type RuleValue = Partial<{
  "prix": boolean,
  "prix . carottes": number,
  "prix . champignons": number,
  "prix . avocat": number,
  "dépenses primeur": number,
  "natureActivite": boolean,
  "natureActivite . industrielle": boolean,
  "natureActivite . commerciale": boolean,
  "natureActivite . agricole": boolean,
  "natureActivite . artisanale": boolean,
  "natureActivite . autreActivite": boolean,
  "situationGeographique": "metropole" | "outremer",
  "entrepriseEnDifficulte": boolean,
  "dateDeCreation": string,
  "activiteNouvelle": boolean,
  "dirigeantsOuActionnairesUniversitaire": boolean,
  "dirigeantsOuActionnairesUniversitaire . etudiant": boolean,
  "dirigeantsOuActionnairesUniversitaire . diplomeMaster": boolean,
  "dirigeantsOuActionnairesUniversitaire . diplomeDoctorat": boolean,
  "dirigeantsOuActionnairesUniversitaire . enseignant": boolean,
  "dirigeantsOuActionnairesUniversitaire . aucune": boolean,
  "valorisationRecherche": boolean,
  "contratValorisation": boolean,
  "capitalDetenu": boolean,
  "capitalDetenu . personnesPhysiques": boolean,
  "capitalDetenu . autreJei": boolean,
  "capitalDetenu . associationFondation": boolean,
  "capitalDetenu . etablissementPublic": boolean,
  "capitalDetenu . societeInvestissement": boolean,
  "capitalDetenu . aucune": boolean,
  /** Chiffre d'affaires de l'année N */
  "chiffreAffairesN": number,
  /** Bilan total de l'année N */
  "bilanTotalN": number,
  /** Effectif de l'année N */
  "effectifTotalN": number,
  /** Chiffre d'affaires de l'année N-1 */
  "chiffreAffairesN1": number,
  /** Bilan total de l'année N-1 */
  "bilanTotalN1": number,
  /** Effectif de l'année N-1 */
  "effectifTotalN1": number,
  /** Chiffre d'affaires de l'année N-2 */
  "chiffreAffairesN2": number,
  /** Bilan total de l'année N-2 */
  "bilanTotalN2": number,
  /** Effectif de l'année N-2 */
  "effectifTotalN2": number,
  "categorieExoneration": boolean,
  "categorieExoneration . jei": boolean,
  "categorieExoneration . repriseEntrepriseEnDifficulte": boolean,
  "categorieExoneration . zoneSpecifique": boolean,
  "categorieExoneration . aucune": boolean,
  "categorieExonerationZoneSpecifique": boolean,
  "categorieExonerationZoneSpecifique . zfr": boolean,
  "categorieExonerationZoneSpecifique . zfuTe": boolean,
  "categorieExonerationZoneSpecifique . ber": boolean,
  "categorieExonerationZoneSpecifique . zrd": boolean,
  "categorieExonerationZoneSpecifique . zfo": boolean,
  "categorieExonerationZoneSpecifique . zrr": boolean,
  "categorieExonerationZoneSpecifique . frr": boolean,
  "categorieExonerationZoneSpecifique . bud": boolean,
  "categorieExonerationZoneSpecifique . zdp": boolean,
  "pourcentageRd": boolean,
  /** L'effectif de l'entreprise est en augmentation */
  "effectifAugmente": boolean,
  /** Les dépenses de l'entreprise sont stables */
  "depensesStables": boolean,
  "depensesRD": boolean,
  "depensesRDAmortissementBiens": boolean,
  "depensesRDAmortissementBiensDom": boolean,
  "depensesRDIndemnisationAssurance": boolean,
  "depensesRDIndemnisationAssuranceDom": boolean,
  "depensesRDChercheursTechniciens": boolean,
  "depensesRDChercheursTechniciensDom": boolean,
  "depensesRDRemunerationInvention": boolean,
  "depensesRDRemunerationInventionDom": boolean,
  "depensesRDRechercheLiensDependance": boolean,
  "depensesRDRechercheLiensDependanceDom": boolean,
  "depensesRDRechercheSansLiensDependance": boolean,
  "depensesRDRechercheSansLiensDependanceDom": boolean,
  "contratOrdc": boolean,
  "respecteCriteresOrdc": boolean,
  "depensesOrdc": number,
  "subventionsOrdc": number,
  "remboursementsSubventionsOrdc": number,
  "depensesRDSubventionsPubliques": number,
  "depensesRDDepensesConseil": number,
  "depensesRDDepensesTiersCir": number,
  "depensesNormalisationSalaires": number,
  "depensesNormalisationSalairesDom": number,
  "depensesNormalisationDirigeant": number,
  "depensesNormalisationDirigeantDom": number,
  "depensesNormalisationRemboursementSubventions": number,
  "depensesNormalisationSubventions": number,
  "depensesNormalisationConseil": number,
  /** Dotations aux amortissements des immobilisations créées ou acquises à l'état neuf et affectées directement à la réalisation d'opérations de conception de prototypes ou installations pilotes de nouveaux produits */
  "depensesPrototypeAmortissementsImmobilisations": number,
  /** Dont dépenses réalisées dans un département d'Outre-mer */
  "depensesPrototypeAmortissementsImmobilisationsDom": number,
  /** Dont dépenses réalisées en Corse */
  "depensesPrototypeAmortissementsImmobilisationsCorse": number,
  /** Chercheurs et techniciens de recherche qui sont directement et exclusivement affectés aux opérations de recherche et développement */
  "depensesPrototypeChercheursTechniciens": number,
  /** Salariés auteurs d'une invention après des opérations de recherche a qui on a versé une rémunération supplémentaire */
  "depensesPrototypeRemunerationInvention": number,
  /** Dotations aux amortissements, frais de prise, de maintenance et de défense des brevets et des certificats d'obtention végétale relatifs aux opérations de conception de prototypes ou installations pilotes de nouveaux produits */
  "depensesPrototypeAmortissementsBrevets": number,
  /** Dont dépenses réalisées dans un département d'Outre-mer */
  "depensesPrototypeAmortissementsBrevetsDom": number,
  /** Dont dépenses réalisées en Corse */
  "depensesPrototypeAmortissementsBrevetsCorse": number,
  /** Frais de dépôt et de défense des dessins et modèles relatifs aux opérations de conception de prototypes ou installations pilotes de nouveaux produits */
  "depensesPrototypeFraisDepotDessins": number,
  /** Dont dépenses réalisées dans un département d'Outre-mer */
  "depensesPrototypeFraisDepotDessinsDom": number,
  /** Dont dépenses réalisées en Corse */
  "depensesPrototypeFraisDepotDessinsCorse": number,
  /** Dépenses afférentes aux opérations de conception de prototypes ou installations pilotes de nouveaux produits dont la réalisation est confiée à des entreprises ou des bureaux d'études et d'ingénierie agréés */
  "depensesPrototypeDepensesSousTraitance": number,
  /** Dont dépenses réalisées dans un département d'Outre-mer */
  "depensesPrototypeDepensesSousTraitanceDom": number,
  /** Dont dépenses réalisées en Corse */
  "depensesPrototypeDepensesSousTraitanceCorse": number,
  /** Montant des remboursements des subventions publiques à ajouter à l'assiette du crédit d'impôt */
  "depensesPrototypeRemboursementsSubventions": number,
  /** Montant des subventions publiques reçues par l'entreprise en raison des opérations de conception de prototypes ou installations pilotes de nouveaux produits */
  "depensesPrototypeSubventionsPubliques": number,
  /** Montant des dépenses exposées auprès de tiers au titre de prestations de conseil pour l'octroi du bénéfice du crédit d'impôt */
  "depensesPrototypeDepensesConseil": number,
  /** Montant des dépenses exposées et facturées pour la réalisation d'opérations de conception de prototypes ou installations pilotes de nouveaux produits pour le compte de tiers bénéficiaire du CII */
  "depensesPrototypeDepensesTiersCii": number,
  "chiffreAffairesSelector": boolean,
  "chiffreAffairesSelector . yearN": boolean,
  "chiffreAffairesSelector . yearN1": boolean,
  "chiffreAffairesSelector . yearN2": boolean,
  "chiffreAffairesSelector . noBilan": boolean,
  "typeDepenses": boolean,
  "typeDepenses . rd": boolean,
  "typeDepenses . normalisation": boolean,
  "typeDepenses . prototype": boolean,
  "performancesSuperieures": boolean,
  "performancesSuperieures . techniques": boolean,
  "performancesSuperieures . eco": boolean,
  "performancesSuperieures . ergonomiques": boolean,
  "performancesSuperieures . fonctionnalites": boolean,
  "performancesSuperieures . performancesSuperieuresAucune": boolean,
  "typeDeRevenus": "bic" | "bnc",
  "regimeFiscal": "micro" | "reel-simplifie" | "reel-normal",
  "typeImposition": "is" | "ir" | "exonere",
  "prototypeDestination": boolean,
  "produitMisMarche": boolean,
  "depensesRdIndemnisationAssuranceDom": boolean,
  "depensesRdIndemnisationAssurance": boolean,
  "depensesRdAmortissementBiensDom": boolean,
  "depensesRdAmortissementBiens": boolean,
  "depensesRdRemunerationInventionDom": boolean,
  "depensesRdRemunerationInvention": boolean,
  "depensesRdChercheursTechniciensDom": boolean,
  "depensesRdChercheursTechniciens": boolean,
  "depensesRdRechercheSansLiensDependanceDom": boolean,
  "depensesRdRechercheSansLiensDependance": boolean,
  "depensesRdRechercheLiensDependanceDom": boolean,
  "depensesRdRechercheLiensDependance": boolean,
  "depensesRdDepensesTiersCir": boolean,
  "depensesRdDepensesConseil": boolean,
  "depensesRdSubventionsPubliques": boolean,
  "depensesNormalisationRemboursementsSubventions": boolean,
  /** Jeune entreprise Universitaire */
  "JEU": boolean,
  /** Éligibilité au statut JEU */
  "JEU . eligibilite": boolean,
  /** JEI */
  "JEI": boolean,
  /** eligibilite au statut JEI */
  "JEI . eligibilite": boolean,
  "JEI . pourcentageRdCondition": boolean,
  /** Jeune Entreprise de Croissance */
  "JEC": boolean,
  /** Éligibilité au statut JEC */
  "JEC . eligibilite": boolean,
  /** L'entreprise est suffisamment jeune pour bénéficier des avantages du statut JEC */
  "JEC . conditionAge": boolean,
  "JEC . critereRD": boolean,
  /** A définir */
  "Jeune Entreprise": boolean,
  /** l'entreprise est elle suffisamment jeune pour bénéficier des avantages du statut JEI */
  "Jeune Entreprise . conditionAge": boolean,
  "ageEntreprise": number,
  "regimeFiscalEstReel": boolean,
  "estUnePME": boolean,
  "CIR": boolean,
  /** Éligibilité au Crédit d'Impôt Recherche */
  "CIR . eligibilite": boolean,
  "CIR . montant": number,
  "CIR . creditMetropole": number,
  "CIR . creditDom": number,
  "CIR . depensesMetropole": number,
  "CIR . depensesDom": number,
  "CIR . deductions": number,
  "CIR . deductions . dom": number,
  "CIR . deductions . metropole": number,
  /** Crédit d'impôt Innovation */
  "CII": boolean,
  /** Eligibilité au CII */
  "CII . eligibilite": boolean,
  /** Montant du Crédit d'Impôt Innovation */
  "CII . montant": number | null,
  "CII . montantPlafonne": number,
  "CII . depensesBase": number,
  "CII . depensesDOM": number,
  "CII . depensesCorse": number,
  "CII . tauxCorse": number,
  "CII . deductions": number,
  "CII . depassementEffectifN": boolean,
  "CII . depassementEffectifN1": boolean,
  "CII . depassementEffectifN2": boolean,
  "CII . depassementFinancierN": boolean,
  "CII . depassementFinancierN1": boolean,
  "CII . depassementFinancierN2": boolean,
  "CII . depassementConsecutif": boolean,
  /** Crédit d'impôt Collaboratif */
  "CICo": boolean,
  /** Eligibilité au CICo */
  "CICo . eligibilite": boolean,
  "CICo . montant": number,
  "CICo . taux": number
}>

/**
 * Subset of the {@link Situation} with only the rules that are questions
 * (i.e. input rules).
 *
 * @note
 * This represents the input rules expected to be provided by the user.
 * Therefore the values are in their JavaScript form (i.e. string constants are
 * enclosed in '' and boolean values are 'true' or 'false').
 */
export type Questions = Partial<{
  /** L'effectif de l'entreprise est en augmentation */
  "effectifAugmente": boolean,
  /** Les dépenses de l'entreprise sont stables */
  "depensesStables": boolean
}>

/**
 * All rule names available in the model.
 */
export type RuleName = keyof Situation

declare let rules: Record<RuleName, Rule>

export default rules
