import { createRequire } from 'node:module'
// @ts-check
import { icons as riCollection } from '@iconify-json/ri'

const require = createRequire(import.meta.url)

/**
 * Liste de nom d'icônes **sans** le préfixe de la collection Remix Icons qui sont utilisées dans l'application
 * Generated by: pnpm detect:icons
 * @type {string[]}
 */
const riIconNames = require('./detected_icons.json')

/**
 * Liste de tuples [collectionDIcônes, tableauDeNomsDIcônesUtiliséesDansLApplication]
 * @type {[import('@iconify/vue').IconifyJSON, string[]][]}
 */
export const collectionsToFilter = [
  [riCollection, riIconNames],
]
