name: CI Tests

on:
  pull_request:
    branches: [main, preprod]
  push:
    branches: [main, preprod]
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Setup Publicodes
        uses: ./.github/actions/setup-publicodes
      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright
      # - name: Lint
      #   run: pnpm lint
      # - name: Typecheck
      #   run: pnpm typecheck
      - name: Test
        run: pnpm test
        env:
          TZ: UTC
          PORT: 3333
          HOST: localhost
          LOG_LEVEL: info
          APP_KEY: yYCr74ySJZRnN1U5VVN6Q4Q77pfFa4x
          NODE_ENV: testing
          SESSION_DRIVER: memory
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_DATABASE: postgres
          APP_NAME: Aides simplifiées
          PUBLIC_APP_URL: http://localhost:3333
          ADMIN_PASSWORD: change-me
          ADMIN_LOGIN: change-me@example.com
          MATOMO_URL: https://stats.beta.gouv.fr/
          MATOMO_TOKEN: your-matomo-token
          MATOMO_SITE_ID: 1
          OPENFISCA_URL: https://openfisca.aides.beta.numerique.gouv.fr/calculate
          LEXIMPACT_URL: https://leximpact.aides.beta.numerique.gouv.fr
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: screenshots
          path: screenshots
          retention-days: 30

      - name: 📊 Upload des rapports d'accessibilité
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: accessibility-reports-${{ github.run_number }}
          path: |
            reports/accessibility/
          retention-days: 30

      - name: 📝 Résumé des violations dans la PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');

            try {
              // Exécuter le script de rapport d'accessibilité
              const reportOutput = execSync('node scripts/accessibility-report.cjs reports/accessibility markdown', {
                encoding: 'utf8',
                maxBuffer: 1024 * 1024 // 1MB buffer pour les gros rapports
              });

              // Créer le commentaire sur la PR
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: reportOutput
              });

            } catch (error) {
              console.log('Aucun rapport d\'accessibilité généré ou erreur:', error.message);

              // Commentaire par défaut si pas de rapport
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '## 🦮 Tests d\'accessibilité\n\n✅ Aucun test d\'accessibilité exécuté ou aucun rapport généré.'
              });
            }

      - name: ❌ Échec si violations critiques
        run: |
          if [ -d "reports/accessibility" ]; then
            cd reports/accessibility
            critical_count=$(grep -r '"impact":"critical"' *.json 2>/dev/null | wc -l || echo "0")
            echo "Violations critiques trouvées: $critical_count"
            if [ "$critical_count" -gt "0" ]; then
              echo "❌ Des violations critiques d'accessibilité ont été détectées"
              echo "Consultez les rapports pour plus de détails"
              exit 1
            fi
          fi
          echo "✅ Aucune violation critique d'accessibilité"
